export const COMPANY = {
  name: "Shree Bhavani Trading Corporation",
  shortName: "Shree Bhavani",
  tagline: "Total Piping Solution",
  established: 1994,
  address: {
    line1: "3,4,5,6 Centre Plaza,",
    line2: "Near Milk Palace, Near H.P Petrol Pump,",
    line3: "Sattadhar Cross Road, Sola Road,",
    city: "Ghatlodia, Ahmedabad",
    pincode: "380061",
    state: "Gujarat",
    full: "3,4,5,6 Centre Plaza, Near Milk Palace, Near H.P Petrol Pump, Sattadhar Cross Road, Sola Road, Ghatlodia, Ahmedabad – 380061",
  },
  phone: {
    primary: "9824017613",
    secondary: "7575001652",
    landline: "27410890",
    display: ["+91 98240 17613", "+91 75750 01652", "0794 2741 0890"],
  },
  email: {
    primary: "bhavanitrading1994@gmail.com",
    display: "bhavanitrading1994@gmail.com",
  },
  whatsapp: "919824017613",
  businessHours: {
    weekdays: "Monday – Saturday: 9:00 AM – 7:00 PM",
    sunday: "Sunday: Closed",
  },
  social: {
    whatsappLink: "https://wa.me/919824017613",
    mapsLink: "https://maps.google.com/?q=Shree+Bhavani+Trading+Corporation+Ghatlodia+Ahmedabad",
  },
} as const;

export const BRANDS = [
  { id: 1, name: "Supreme", color: "#E63946", description: "India's leading polymer products manufacturer" },
  { id: 2, name: "Lifeline", color: "#457B9D", description: "Premium plumbing systems" },
  { id: 3, name: "Aqua Gold", color: "#2A9D8F", description: "Quality water management solutions" },
  { id: 4, name: "Formcore", color: "#E9C46A", description: "Industrial piping solutions" },
  { id: 5, name: "FlameGuard", color: "#F4A261", description: "Fire protection systems" },
  { id: 6, name: "Serene", color: "#6D6875", description: "Sanitary and bathroom solutions" },
  { id: 7, name: "e-Lite", color: "#48CAE4", description: "Modern electrical conduit systems" },
  { id: 8, name: "NeoSeal", color: "#3D405B", description: "Advanced sealing solutions" },
  { id: 9, name: "Zoloto", color: "#C77DFF", description: "Premium valve manufacturer" },
  { id: 10, name: "RBI", color: "#2D6A4F", description: "Reliable brass fittings" },
  { id: 11, name: "Indiano", color: "#023E8A", description: "Agricultural piping systems" },
  { id: 12, name: "Somex", color: "#6A040F", description: "Drainage solutions" },
  { id: 13, name: "Felice", color: "#7B2D8B", description: "Bathroom accessories" },
  { id: 14, name: "Thor", color: "#1B4332", description: "Industrial strength fittings" },
  { id: 15, name: "Dutron", color: "#0077B6", description: "UPVC pipe systems" },
  { id: 16, name: "Simtex", color: "#CB4335", description: "Waterproofing solutions" },
] as const;

export const PRODUCT_CATEGORIES = [
  {
    id: 1,
    name: "UPVC Pipes & Fittings",
    slug: "upvc-pipes-fittings",
    icon: "🔧",
    description: "High-pressure UPVC pipes for water supply and industrial use",
    count: 45,
  },
  {
    id: 2,
    name: "CPVC Pipes & Fittings",
    slug: "cpvc-pipes-fittings",
    icon: "🌡️",
    description: "Hot & cold water CPVC piping systems",
    count: 38,
  },
  {
    id: 3,
    name: "PVC Agri Pipes",
    slug: "pvc-agri-pipes",
    icon: "🌾",
    description: "Agricultural irrigation PVC pipe solutions",
    count: 22,
  },
  {
    id: 4,
    name: "SWR Pipes & Fittings",
    slug: "swr-pipes-fittings",
    icon: "🏗️",
    description: "Soil, waste & rainwater drainage systems",
    count: 31,
  },
  {
    id: 5,
    name: "Underground Drainage",
    slug: "underground-drainage",
    icon: "⬇️",
    description: "Underground structured wall pipes & chambers",
    count: 18,
  },
  {
    id: 6,
    name: "Fire Sprinkler Systems",
    slug: "fire-sprinkler-systems",
    icon: "🔥",
    description: "Certified fire protection sprinkler systems",
    count: 15,
  },
  {
    id: 7,
    name: "PP Low Noise Pipes",
    slug: "pp-low-noise-pipes",
    icon: "🔇",
    description: "Polypropylene low-noise drainage systems",
    count: 12,
  },
  {
    id: 8,
    name: "PEX Pipes",
    slug: "pex-pipes",
    icon: "💧",
    description: "Cross-linked polyethylene flexible piping",
    count: 10,
  },
  {
    id: 9,
    name: "Brass Fittings",
    slug: "brass-fittings",
    icon: "🔩",
    description: "Premium brass pipe fittings & connectors",
    count: 56,
  },
  {
    id: 10,
    name: "Ball Valves",
    slug: "ball-valves",
    icon: "🚰",
    description: "Industrial & domestic ball valves",
    count: 34,
  },
  {
    id: 11,
    name: "Butterfly Valves",
    slug: "butterfly-valves",
    icon: "🦋",
    description: "Flow control butterfly valves",
    count: 20,
  },
  {
    id: 12,
    name: "Check Valves",
    slug: "check-valves",
    icon: "✅",
    description: "Non-return check valves",
    count: 16,
  },
  {
    id: 13,
    name: "Plumbing Accessories",
    slug: "plumbing-accessories",
    icon: "🔨",
    description: "Complete plumbing hardware accessories",
    count: 68,
  },
  {
    id: 14,
    name: "Bathroom Fittings",
    slug: "bathroom-fittings",
    icon: "🚿",
    description: "Designer bathroom fittings & fixtures",
    count: 42,
  },
  {
    id: 15,
    name: "Waterproofing Chemicals",
    slug: "waterproofing-chemicals",
    icon: "🧪",
    description: "Construction waterproofing solutions",
    count: 25,
  },
  {
    id: 16,
    name: "Adhesives & Sealants",
    slug: "adhesives-sealants",
    icon: "🔐",
    description: "Industrial adhesives and pipe sealants",
    count: 19,
  },
  {
    id: 17,
    name: "Water Tanks",
    slug: "water-tanks",
    icon: "🫙",
    description: "Overhead & underground storage tanks",
    count: 14,
  },
  {
    id: 18,
    name: "Manhole Covers",
    slug: "manhole-covers",
    icon: "🔲",
    description: "Heavy-duty manhole covers & frames",
    count: 8,
  },
  {
    id: 19,
    name: "Drainage Products",
    slug: "drainage-products",
    icon: "🌊",
    description: "Channel drains & drainage accessories",
    count: 22,
  },
  {
    id: 20,
    name: "Pipe Clamps",
    slug: "pipe-clamps",
    icon: "🔗",
    description: "Heavy-duty pipe clamps & supports",
    count: 30,
  },
  {
    id: 21,
    name: "Industrial Valves",
    slug: "industrial-valves",
    icon: "⚙️",
    description: "Gate, globe & pressure relief valves",
    count: 28,
  },
] as const;

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rajesh Patel",
    company: "Patel Construction Co.",
    designation: "Project Manager",
    content: "Shree Bhavani has been our go-to supplier for all piping requirements for the past 8 years. Their product quality and prompt delivery is unmatched in Ahmedabad.",
    rating: 5,
  },
  {
    id: 2,
    name: "Amit Shah",
    company: "Shah Builders & Developers",
    designation: "Director",
    content: "Excellent range of products and very competitive wholesale pricing. The technical team helped us select the right fire sprinkler system for our commercial project.",
    rating: 5,
  },
  {
    id: 3,
    name: "Suresh Kumar",
    company: "Kumar Plumbing Services",
    designation: "Owner",
    content: "Best supplier in Ahmedabad for UPVC and CPVC pipes. Always have stock available and the staff is very knowledgeable about products.",
    rating: 5,
  },
  {
    id: 4,
    name: "Priya Mehta",
    company: "Mehta Infrastructure Ltd.",
    designation: "Purchase Manager",
    content: "We source all our waterproofing chemicals and drainage systems from Bhavani Trading. 30 years of experience shows in their product recommendations.",
    rating: 5,
  },
  {
    id: 5,
    name: "Dinesh Agrawal",
    company: "Agrawal Housing Board",
    designation: "Chief Engineer",
    content: "Authorized distributor for all major brands. Certificate of authenticity provided with every order. Highly recommended for government and commercial projects.",
    rating: 5,
  },
] as const;

export const STATS = [
  { label: "Years of Experience", value: "30+", suffix: "" },
  { label: "Products in Stock", value: "500", suffix: "+" },
  { label: "Brands Represented", value: "16", suffix: "+" },
  { label: "Happy Clients", value: "2000", suffix: "+" },
] as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Products", href: "/products" },
  { label: "Brands", href: "/brands" },
  { label: "Contact", href: "/contact" },
] as const;

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080/api";
